[theme]
primaryColor = "#007AC1"           # Amplar blue (used in "Our health solutions")
backgroundColor = "#f5f7f8"        # Very light grey (background tone)
secondaryBackgroundColor = "#ffffff"  # Cards or sidebar
textColor = "#4A4A4A"              # Dark warm grey (used for body text)
font = "sans serif"

